version: '3'

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ./data/data:/data/db
      - ./data/logs:/data/logs
    ports:
      - 27017:27017
    networks:
      - mongodb_go_examples_net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@192.168.170.66:27017/

networks:
  mongodb_go_examples_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.3.0/16